apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.image.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s.custom.controller: k8s-custom-controller
  template:
    metadata:
      labels:
        k8s.custom.controller: k8s-custom-controller
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          volumeMounts:
            - name: {{ .Values.webhook.volumeMounts }}
              mountPath: /certs
              readOnly: true
          env:
            - name: TLS_CERT_FILE
              value: "/certs/tls.crt"
            - name: TLS_KEY_FILE
              value: "/certs/tls.key"
            - name: CONTEXT
              value: "kind-practice"
      volumes:
        - name: {{ .Values.webhook.volumeMounts }}
          secret:
            secretName: "{{ .Chart.Name }}-tls"