apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
  annotations:
    cert-manager.io/inject-ca-from: "{{ .Values.image.namespace }}/{{ .Values.webhook.name }}-certificate"
webhooks:
  - name: "{{ include "chart.fullname" . }}.{{ .Values.image.namespace }}.svc"
    admissionReviewVersions:
      - v1
    sideEffects: None
    timeoutSeconds: 30
    clientConfig:
      service:
        name: {{ include "chart.fullname" . }}
        namespace: {{ .Values.image.namespace }}
        path: /validate
        port: {{ .Values.service.port }}
    rules:
      - apiGroups: [ "apps" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "deployments" ]
    failurePolicy: Fail