kind: PersistentVolume
apiVersion: v1
metadata:
  name: trivy-cache-pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
#  hostPath:
#    path: "/opt/postgres-data"