apiVersion: v1
kind: Service
metadata:
  name: trivy-server-service
  namespace: default
  labels:
    app: trivy-server
spec:
  selector:
    app: trivy-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP # Use ClusterIP for internal access, or NodePort/LoadBalancer for external access

# [service-name].[service-namespace].svc:8080
# trivy-server-service.default.svc:8080