apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: k8s-controller-tls
  namespace: default
spec:
  secretName: k8s-controller-tls
  dnsNames:
    - k8s-custom-controller-service
    - k8s-custom-controller-service.default
    - k8s-custom-controller-service.default.svc
    - k8s-custom-controller-service.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer  # You'll need to create this
    kind: ClusterIssuer