apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-custom-controller-webhook
webhooks:
  - name: k8s-custom-controller-service.default.svc
    clientConfig:
      service:
        name: k8s-custom-controller-service
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQ4ekNDQXR1Z0F3SUJBZ0lVY0tpWk5uVGVGMVJYZFBpcDJOSUE0djljdEtRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERXlNREFHQTFVRUF3d3Bhemh6TFdOMWMzUnZiUzFqYjI1MGNtOXNiR1Z5TFhObGNuWnBZMlV1WkdWbQpZWFZzZEM1emRtTXdIaGNOTWpVd056STJNVGt5TkRFMldoY05Nall3TnpJMk1Ua3lOREUyV2pBME1USXdNQVlEClZRUUREQ2xyT0hNdFkzVnpkRzl0TFdOdmJuUnliMnhzWlhJdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMll6Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNSko4SkhFOFhPZkJhYUN0cEd4dUNUagpudis0RlUxSDhxK3hTWDl3ZVRrdVRnd2pwUTAyWUtWRWFOdHZRelo3S3BkNmlXZUVvK0JKWnhPanIxRzRIRFc4CnBHbmVMMVJtRFRkaUxuV0NBeUd3ZkN4a1BCM2hoR2FXMWJiVXQxdVRxNW5ycjlTVUI2NUZzaDBPSG9jVXUzeGoKOCtsVnFYcVNLT21yTk5KWHlUbUtFN1dRM3BVMURuUTNOSlJ4RVBUZFZQWE5zdjJscmE1RW5jMmxleW1HMDBvVQo4cjN3YWF3RVRGaTBzM2Q4ZHk5cFhBZjRUQU93UzFwVGpOT01za0kremZWSEQzSmw0VDdRTWdYL1NaNkwwMng3CndYRm4wU2QvOURQZlprNWN5U0pKQ3ZhOFBmaGx1Zjh2YUZDVTYyNkZjbTRQM1VYMjQxSmtLcWxmbXpQZk5rMEMKQXdFQUFhT0IvRENCK1RBTEJnTlZIUThFQkFNQ0JEQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3Z2JVRwpBMVVkRVFTQnJUQ0Jxb0lkYXpoekxXTjFjM1J2YlMxamIyNTBjbTlzYkdWeUxYTmxjblpwWTJXQ0pXczRjeTFqCmRYTjBiMjB0WTI5dWRISnZiR3hsY2kxelpYSjJhV05sTG1SbFptRjFiSFNDS1dzNGN5MWpkWE4wYjIwdFkyOXUKZEhKdmJHeGxjaTF6WlhKMmFXTmxMbVJsWm1GMWJIUXVjM1pqZ2pkck9ITXRZM1Z6ZEc5dExXTnZiblJ5YjJ4cwpaWEl0YzJWeWRtbGpaUzVrWldaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNQjBHQTFVZERnUVdCQlRRCmtVbER4dDZwZFowY2t1Tk9VckVlQXkwSHJUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFJZnpNZm1laVFVclYKZUgzZFZtL0swMGJjRzFpSE5lRDlhT0IxRCtqZ2dQTWdrUzNpNDNsbjlnNW1BS08wZEs3d1J5UVVsL3VtMkhYOAplSUlqSVIvNHhlSzk2S0I2ZkdlUlMvd2F5cC9iRWR3aUdzY0xMSnRja0psVThoM0M1d0orT2pNei9HT1ArNDhBCmhJL1lhblpvRDdnTGI4aDgxMVFUcVg0TjZ1NUtHLzljOTFaM0E3c1d1UFNrREpCeTJCVXNwVklMa2F0dUNvcGIKb1owaWplT0haUSs4b3BuMG95K2xnRllPdU5FL1ZLWitnNmlsOGpWeDBwcWR3SWpHdCtaT3RlRkZEZnNTdGZ1OAp1U3JBdDR4ZitEWjNpSnNzbDVoOEliUnF3RHVBNnlXcTFmTVRjbEpIQTYyNlRNRjBXODJMV1BvT0wzK29ramczCmdtMFQxeVJQS0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
    namespaceSelector: {}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    failurePolicy: Fail