apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: k8s-custom-controller-service
webhooks:
  - name: k8s-custom-controller-service.default.svc
    admissionReviewVersions: ["v1"]
    sideEffects: None
    clientConfig:
      service:
        name: k8s-custom-controller-service
        namespace: default
        path: "/validate"
        port: 443
      caBundle: |
        LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURsVENDQW4yZ0F3SUJBZ0lVTlhEZlJiMGVVVkdYeG9rckx0ek1FeWMzWHRJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERXlNREFHQTFVRUF3d3Bhemh6TFdOMWMzUnZiUzFqYjI1MGNtOXNiR1Z5TFhObGNuWnBZMlV1WkdWbQpZWFZzZEM1emRtTXdIaGNOTWpVd056STJNVGt4T0RRMFdoY05Nall3TnpJMk1Ua3hPRFEwV2pBME1USXdNQVlEClZRUUREQ2xyT0hNdFkzVnpkRzl0TFdOdmJuUnliMnhzWlhJdGMyVnlkbWxqWlM1a1pXWmhkV3gwTG5OMll6Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLUFdZQ2VTRlFORmp0VkZpVWRxRFFydApPcGpBMS9zaCt6K2VMMjF0ZzM3Z1lyNEhMVWJNOEg2UHRLcGc4N3Z4eURXL2FXL1JlSWlFMDdRU0ZoeWJlUk9NCjJseGlDeHpWUFZBdXZLdGNDNTVpQ1NRUWEvNVJuMmVGeWpWMzYwOFF4a041eWw5Y2NDZkZYRmJmYVJMenBvUXUKQ3k3SXVIb1RNWkNNT1hCQitZTDZuekJoM0J4c3dGMUNFanZuSU1XR1Bja0hMQ1V0L2NqeDQxa0tPYlR6SDl5cApYR2Z3anJjVy9iVkNzd1MrbExzdE5jbDRXenBrd012VndoaWYrOVdzUXRwOEpoMXFDQlVSQnFFUVBBWE56dStOClZnVmExRmhkeFVrNDlGUXZKbytXd2x0RlJvZzdBT1ZaRjY2ZmxueFFPalBQNTF4eURqRHRKWUlJK09mZ1g4Y0MKQXdFQUFhT0JuakNCbXpCNkJnTlZIUkVFY3pCeGdpbHJPSE10WTNWemRHOXRMV052Ym5SeWIyeHNaWEl0YzJWeQpkbWxqWlM1a1pXWmhkV3gwTG5OMlk0SWRhemh6TFdOMWMzUnZiUzFqYjI1MGNtOXNiR1Z5TFhObGNuWnBZMldDCkpXczRjeTFqZFhOMGIyMHRZMjl1ZEhKdmJHeGxjaTF6WlhKMmFXTmxMbVJsWm1GMWJIUXdIUVlEVlIwT0JCWUUKRkFuaGdjT3JZZUxOd0RhZnpySXZxYld1ZU12QU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQTd0Wll0a1BqTApQZWFTdmluOWMySlRaeWgwK1g1K1IwMWY2WWZZYXArU0JIbTd0aXR2MEJKR1NpVGZYWVFmcnhPMXJqZzRmdWNWCnpyMW01NlBWR1AvTktLenphUi8wMTZtNEVzVGFHV2g1Q2FySkt2K3JTcUZjSEkzQ1pwUXZ2bG5SMmlhZFBxSW8KUGlZRzlHbzVaNFNzVjRzZDNXR0ZZajBhR3BuTmgxTlF1ZFRUYkkyT002OHNFRkEwR0VVWFNDTlBQWFdSMGxjWAplcXNhbFRxRVJNOTlnYmJGQnlkUllQSG50elB1MkZSbVllbjR1UkpnMExkMHR0S3Y3N2x3cWtOOGQreEpOaUdECi9MUkhLSWVrZ0xkelJmOHd0OFBiMHpqY1IyZmtCYVkvQWh4Z0FQaVpsekRzU0QwNHFCZGhYV0Z6ck1Od3VrYUkKWUVZRHRKWG9FOWZDCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    rules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["deployments"]
    failurePolicy: Fail
