name: Slash Command Handler

on:
  issue_comment:
    types: [created]

jobs:
  slash-command:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/slash-command-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commands: |
            lgtm
#            assign